### PR TITLE
fix: Fix logger formatting

### LINKED ISSUE #564: Logger cannot highlight strings properly.
Was working fine in logs rework (https://github.com/GabuTheDev/tosu/commit/c2fac7ea7409bdbebb0c84a1bea6085aafc29172)
regressed in ck's rewrite (https://github.com/tosuapp/tosu/commit/6bb07c220c8ccc39a9bc3cb9a0f9c21ae8878a6f)

my regex was that long for a reason :/

1. multiple words are not getting highlighted.

Image

2. the char `%` cannot be escaped anymore.

In my commit, doing `This is at %96\% progress%` could property select and highlight `96% progress`.

### PR DESCRIPTION
**Pull request by cyperdark**
closes #564

### CODE REVIEW

File: packages/common/utils/logger.ts [hunk 1]
```diff
@@ -10,6 +10,7 @@ import { ensureDirectoryExists, getDataPath } from './directories';
 import { progressManager } from './progress';
 
 const HighlightColor = '\x1b[1m\x1b[37m';
+const HighlightRegex = /%%(.*?)%%/g;
```
Comment (GabuTheDev) [inline packages/common/utils/logger.ts]: Why the double percent symbol?
Why would we want to change from `%` to `%%` instead of using the escape symbol as everybody else?

Comment (GabuTheDev) [reply packages/common/utils/logger.ts]: > i have no clue what this abomination of regex does

It's just a regex that uses grouping.

`(^|[\s([])%`: looks for a `%` that has a whitespace before it, or the string starts with it.
`((?:\\.|[^%\\])+)` everything in-between two `%`, ignoreing `\%`
`%(?=[.,:;!?\s)\]]|$)` checks for ending with % that has either space after, punctuation, or brackets, so like, basic cases with symbols.
`(\\%)`: this one is to make sure `\%` are escaped.

> first time hearing about this one

ever used `\n`? or `\r`? `\\` ? the `\` before another ascii symbol is to escape them.
https://developer.mozilla.org/en-US/docs/Glossary/Escape_character
