### PR TITLE
fix: pp calc improvements

### LINKED ISSUE #351: Passing a floating-point negative number to rosu causes errors.
The `updateStarsAndPerformance` functions throws an error due to `invalid type`. Error passed via wasm (rosu).
We're passing a negative float number through one of the properties of a performance calculator func or rosu returns a negative value through wasm, which expects an u32.

There are more chances of being the later one, because the user reported that the value decreases over time (meaning it is accumulating negatively lol).

Image

Repoted on discord by `matthieu103` | [message link](https://discord.com/channels/1056534107330445362/1185957776665628764/1372637336558506094)

### PR DESCRIPTION
**Pull request by GabuTheDev**
This PR fixes some issues regarding performance points calculation, specifically:

- [x] [Fixes noticeable pp fc calc performance degradation for the Mania ruleset.](https://discord.com/channels/1056534107330445362/1185957776665628764/1375229211018657983)
- [x] Fixes pp calc for FC (now the value should only decrease from it's maximum value)
- [x] Changes pp value assignment order. (if one fails, it shouldn't stop the others from updating)
- [x] Fixes #351 
- [x] Some refactoring.. nothing crazy

tested on both lazer and stable. (I've learned my lesson..)

### CODE REVIEW

File: packages/tosu/src/states/gameplay.ts [hunk 1]
```diff
@@ -508,39 +508,44 @@ export class Gameplay extends AbstractState {
...
             ) {
-                if (this.gradualPerformance) this.gradualPerformance.free();
-                if (this.performanceAttributes)
-                    this.performanceAttributes.free();
-
-                const difficulty = new rosu.Difficulty({
-                    mods: removeDebuffMods(this.mods.array),
-                    lazer: this.game.client === ClientType.lazer
-                });
+                [this.gradualPerformance, this.performanceAttributes].forEach(
```
Comment (cyperdark) [inline packages/tosu/src/states/gameplay.ts:522]: dont do that

File: packages/tosu/src/states/gameplay.ts [hunk 2]
```diff
@@ -508,39 +508,44 @@ export class Gameplay extends AbstractState {
             const currentState = `${menu.checksum}:${menu.gamemode}:${this.mods.checksum}:${menu.mp3Length}`;
             const isUpdate = this.previousState !== currentState;
 
+            const commonOptions = {
```
Comment (cyperdark) [inline packages/tosu/src/states/gameplay.ts:511]: commonParams

File: packages/tosu/src/states/gameplay.ts [hunk 3]
```diff
@@ -508,39 +508,44 @@ export class Gameplay extends AbstractState {
...
-                }).calculate(currentBeatmap);
+                this.performanceAttributes = new rosu.Performance(
+                    commonOptions
+                ).calculate(currentBeatmap);
 
                 this.previousState = currentState;
             }
 
             if (!this.gradualPerformance || !this.performanceAttributes) {
+                const missingComponents = {
```
Comment (cyperdark) [inline packages/tosu/src/states/gameplay.ts:540]: do not create new object for that

File: packages/tosu/src/states/gameplay.ts [hunk 4]
```diff
@@ -508,39 +508,44 @@ export class Gameplay extends AbstractState {
...
+                    gradualPerformance: !this.gradualPerformance,
+                    performanceAttributes: !this.performanceAttributes
+                };
                 wLogger.debug(
                     ClientType[this.game.client],
                     this.game.pid,
-                    `gameplay updateStarsAndPerformance One of the things not ready`,
-                    `gradual: ${this.gradualPerformance === undefined} - attributes: ${this.performanceAttributes === undefined}`
+                    'gameplay updateStarsAndPerformance: Missing required components',
+                    JSON.stringify(missingComponents)
```
Comment (cyperdark) [inline packages/tosu/src/states/gameplay.ts:548]: dont

File: packages/tosu/src/states/gameplay.ts [hunk 5]
```diff
@@ -558,67 +563,79 @@ export class Gameplay extends AbstractState {
...
             if (fcPerformance) {
                 beatmapPP.currAttributes.fcPP = fcPerformance.pp;
                 beatmapPP.updatePPAttributes('fc', fcPerformance);
             }
 
+            const maxAchievablePerformance = new rosu.Performance({
+                ...calcOptions,
+                misses: this.hitMiss
+            }).calculate(this.performanceAttributes);
+
```
Comment (cyperdark) [inline packages/tosu/src/states/gameplay.ts:638]: why you are doing `...calcOptions,` when you can set `calcOptions.misses = 0;` and pass calcOptions as it is, and update `calcOptions.misses = this.hitMiss;`

instead of making copy of all objects twice

**Review by cyperdark — CHANGES_REQUESTED** [review]

File: packages/tosu/src/states/gameplay.ts (hunk 1 above)
Comment (GabuTheDev) [reply packages/tosu/src/states/gameplay.ts:522]: any reasons?

File: packages/tosu/src/states/gameplay.ts (hunk 5 above)
Comment (GabuTheDev) [reply packages/tosu/src/states/gameplay.ts:638]: This is ensuring `calcOptions` is not being modified throught the calcs.
While you're right, it creates copies, I believe this is more of a preference instead of a "performance" issue, if that's why you pointed this out.

File: packages/tosu/src/states/gameplay.ts (hunk 1 above)
Comment (cyperdark) [reply packages/tosu/src/states/gameplay.ts:522]: why you need foreach on two simple conditions?

**Review by cyperdark — APPROVED** [review]
